# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linuxmint/Schreibtisch/HWP/HWPRobot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linuxmint/Schreibtisch/HWP/HWPRobot/Debug

# Utility rule file for upload_HWPRobot_eeprom.

# Include any custom commands dependencies for this target.
include CMakeFiles/upload_HWPRobot_eeprom.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/upload_HWPRobot_eeprom.dir/progress.make

CMakeFiles/upload_HWPRobot_eeprom: HWPRobot.eep
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/linuxmint/Schreibtisch/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Uploading HWPRobot.eep to atmega1280 using avr109"
	avrdude -p atmega1280 -c avr109 -U eeprom:w:HWPRobot.eep -P usb

HWPRobot.eep: HWPRobot.elf
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/home/linuxmint/Schreibtisch/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Generating HWPRobot.eep"
	/bin/avr-objcopy -j .eeprom --set-section-flags=.eeprom=alloc,load --change-section-lma .eeprom=0 --no-change-warnings -O ihex HWPRobot.elf HWPRobot.eep

upload_HWPRobot_eeprom: CMakeFiles/upload_HWPRobot_eeprom
upload_HWPRobot_eeprom: HWPRobot.eep
upload_HWPRobot_eeprom: CMakeFiles/upload_HWPRobot_eeprom.dir/build.make
.PHONY : upload_HWPRobot_eeprom

# Rule to build all files generated by this target.
CMakeFiles/upload_HWPRobot_eeprom.dir/build: upload_HWPRobot_eeprom
.PHONY : CMakeFiles/upload_HWPRobot_eeprom.dir/build

CMakeFiles/upload_HWPRobot_eeprom.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/upload_HWPRobot_eeprom.dir/cmake_clean.cmake
.PHONY : CMakeFiles/upload_HWPRobot_eeprom.dir/clean

CMakeFiles/upload_HWPRobot_eeprom.dir/depend:
	cd /home/linuxmint/Schreibtisch/HWP/HWPRobot/Debug && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/linuxmint/Schreibtisch/HWP/HWPRobot /home/linuxmint/Schreibtisch/HWP/HWPRobot /home/linuxmint/Schreibtisch/HWP/HWPRobot/Debug /home/linuxmint/Schreibtisch/HWP/HWPRobot/Debug /home/linuxmint/Schreibtisch/HWP/HWPRobot/Debug/CMakeFiles/upload_HWPRobot_eeprom.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/upload_HWPRobot_eeprom.dir/depend

