# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lorenz/Desktop/HWP/HWPRobot

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lorenz/Desktop/HWP/HWPRobot/Debug

# Include any dependencies generated for this target.
include CMakeFiles/HWPRobot.elf.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/HWPRobot.elf.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/HWPRobot.elf.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/HWPRobot.elf.dir/flags.make

CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/communication/communication.c
CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/communication/communication.c

CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/communication/communication.c > CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.i

CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/communication/communication.c -o CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.s

CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/io/adc/adc.c
CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/io/adc/adc.c

CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/io/adc/adc.c > CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.i

CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/io/adc/adc.c -o CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.s

CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/io/adc/adc_isr.S
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building ASM object CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.obj"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -o CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/io/adc/adc_isr.S

CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing ASM source to CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.i"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/io/adc/adc_isr.S > CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.i

CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling ASM source to assembly CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.s"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/io/adc/adc_isr.S -o CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.s

CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/io/i2c/i2c.c
CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/io/i2c/i2c.c

CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/io/i2c/i2c.c > CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.i

CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/io/i2c/i2c.c -o CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.s

CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/io/uart/uart.c
CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/io/uart/uart.c

CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/io/uart/uart.c > CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.i

CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/io/uart/uart.c -o CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.s

CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/io/uart/uart_isr.S
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building ASM object CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.obj"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -o CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/io/uart/uart_isr.S

CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing ASM source to CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.i"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/io/uart/uart_isr.S > CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.i

CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling ASM source to assembly CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.s"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/io/uart/uart_isr.S -o CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.s

CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/motor/motor.c
CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/motor/motor.c

CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/motor/motor.c > CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.i

CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/motor/motor.c -o CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.s

CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/pathFollower/pathFollower.c
CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/pathFollower/pathFollower.c

CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/pathFollower/pathFollower.c > CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.i

CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/pathFollower/pathFollower.c -o CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.s

CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/labyrinth/labyrinth.c
CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/labyrinth/labyrinth.c

CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/labyrinth/labyrinth.c > CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.i

CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/labyrinth/labyrinth.c -o CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.s

CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/remoteDataProcessing/remoteDataProcessing.c
CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/remoteDataProcessing/remoteDataProcessing.c

CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/remoteDataProcessing/remoteDataProcessing.c > CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.i

CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/remoteDataProcessing/remoteDataProcessing.c -o CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.s

CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/timeTask/timeTask.c
CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building C object CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj -MF CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/timeTask/timeTask.c

CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/timeTask/timeTask.c > CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.i

CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/timeTask/timeTask.c -o CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.s

CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.obj: /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/timeTask/timeTask_isr.S
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building ASM object CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.obj"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -o CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.obj -c /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/timeTask/timeTask_isr.S

CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing ASM source to CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.i"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/timeTask/timeTask_isr.S > CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.i

CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling ASM source to assembly CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.s"
	/usr/bin/avr-gcc $(ASM_DEFINES) $(ASM_INCLUDES) $(ASM_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/lib/tools/timeTask/timeTask_isr.S -o CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.s

CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/src/badISR.c
CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building C object CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj -MF CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/src/badISR.c

CMakeFiles/HWPRobot.elf.dir/src/badISR.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/src/badISR.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/src/badISR.c > CMakeFiles/HWPRobot.elf.dir/src/badISR.c.i

CMakeFiles/HWPRobot.elf.dir/src/badISR.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/src/badISR.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/src/badISR.c -o CMakeFiles/HWPRobot.elf.dir/src/badISR.c.s

CMakeFiles/HWPRobot.elf.dir/src/main.c.obj: CMakeFiles/HWPRobot.elf.dir/flags.make
CMakeFiles/HWPRobot.elf.dir/src/main.c.obj: /home/lorenz/Desktop/HWP/HWPRobot/src/main.c
CMakeFiles/HWPRobot.elf.dir/src/main.c.obj: CMakeFiles/HWPRobot.elf.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building C object CMakeFiles/HWPRobot.elf.dir/src/main.c.obj"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -MD -MT CMakeFiles/HWPRobot.elf.dir/src/main.c.obj -MF CMakeFiles/HWPRobot.elf.dir/src/main.c.obj.d -o CMakeFiles/HWPRobot.elf.dir/src/main.c.obj -c /home/lorenz/Desktop/HWP/HWPRobot/src/main.c

CMakeFiles/HWPRobot.elf.dir/src/main.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing C source to CMakeFiles/HWPRobot.elf.dir/src/main.c.i"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E /home/lorenz/Desktop/HWP/HWPRobot/src/main.c > CMakeFiles/HWPRobot.elf.dir/src/main.c.i

CMakeFiles/HWPRobot.elf.dir/src/main.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling C source to assembly CMakeFiles/HWPRobot.elf.dir/src/main.c.s"
	/usr/bin/avr-gcc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S /home/lorenz/Desktop/HWP/HWPRobot/src/main.c -o CMakeFiles/HWPRobot.elf.dir/src/main.c.s

# Object files for target HWPRobot.elf
HWPRobot_elf_OBJECTS = \
"CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.obj" \
"CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj" \
"CMakeFiles/HWPRobot.elf.dir/src/main.c.obj"

# External object files for target HWPRobot.elf
HWPRobot_elf_EXTERNAL_OBJECTS =

HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/communication/communication.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/io/adc/adc_isr.S.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/io/i2c/i2c.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/io/uart/uart_isr.S.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/motor/motor.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/pathFollower/pathFollower.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/tools/labyrinth/labyrinth.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/tools/remoteDataProcessing/remoteDataProcessing.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/lib/tools/timeTask/timeTask_isr.S.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/src/badISR.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/src/main.c.obj
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/build.make
HWPRobot.elf: CMakeFiles/HWPRobot.elf.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=/home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Linking C executable HWPRobot.elf"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/HWPRobot.elf.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/HWPRobot.elf.dir/build: HWPRobot.elf
.PHONY : CMakeFiles/HWPRobot.elf.dir/build

CMakeFiles/HWPRobot.elf.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/HWPRobot.elf.dir/cmake_clean.cmake
.PHONY : CMakeFiles/HWPRobot.elf.dir/clean

CMakeFiles/HWPRobot.elf.dir/depend:
	cd /home/lorenz/Desktop/HWP/HWPRobot/Debug && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/lorenz/Desktop/HWP/HWPRobot /home/lorenz/Desktop/HWP/HWPRobot /home/lorenz/Desktop/HWP/HWPRobot/Debug /home/lorenz/Desktop/HWP/HWPRobot/Debug /home/lorenz/Desktop/HWP/HWPRobot/Debug/CMakeFiles/HWPRobot.elf.dir/DependInfo.cmake "--color=$(COLOR)"
.PHONY : CMakeFiles/HWPRobot.elf.dir/depend

