# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# compile ASM with /bin/avr-gcc
# compile C with /bin/avr-gcc
ASM_DEFINES = -DF_CPU=8000000UL

ASM_INCLUDES = -I/home/linuxmint/Schreibtisch/HWP/HWPRobot/lib -I/home/linuxmint/Schreibtisch/HWP/HWPRobot/src

ASM_FLAGS = -O2 -g2 -g -mmcu=atmega1280 -x assembler-with-cpp -c -fpack-struct -fshort-enums -funsigned-char -funsigned-bitfields -ffunction-sections -fdata-sections -Wall -Wextra -Wpedantic -std=gnu99

C_DEFINES = -DF_CPU=8000000UL

C_INCLUDES = -I/home/linuxmint/Schreibtisch/HWP/HWPRobot/lib -I/home/linuxmint/Schreibtisch/HWP/HWPRobot/src

C_FLAGS = -O2 -g2 -g -mmcu=atmega1280 -c -fpack-struct -fshort-enums -funsigned-char -funsigned-bitfields -ffunction-sections -fdata-sections -Wall -Wextra -Wpedantic -std=gnu99

